name: template
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.8
  awesome_notifications: ^0.11.0
  firebase_messaging: ^16.1.2
  flutter_secure_storage: ^10.0.0
  injectable: ^2.7.1+4
  get_it: ^9.2.1
  flutter_screenutil: ^5.9.3
  dartz: ^0.10.1
  bot_toast: ^4.1.3
  flutter_animate: ^4.5.2
  font_awesome_flutter: ^11.0.0
  easy_localization: ^3.0.8
  dio: ^5.9.2
  logger: ^2.6.2
  flutter_bloc: ^9.1.1
  firebase_core: ^4.5.0
  freezed_annotation: ^3.1.0
  phone_parser: ^0.0.7
  country_code_picker: ^3.4.1
  android_package_installer: ^0.0.3
  firebase_analytics: ^12.3.0
  http: ^1.5.0
  package_info_plus: ^9.0.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.12.2
  injectable_generator: ^2.12.1
  mocktail: ^1.0.4
  freezed: ^3.2.5
  json_serializable: ^6.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/translations/